In [1]:
import pandas as pd
 
data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

In [2]:
data

[['Alice', 25], ['Bob', 30], ['Charlie', 35]]

In [3]:
pd.DataFrame(data,columns=["name","col"])

      name  col
0    Alice   25
1      Bob   30
2  Charlie   35

In [4]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

In [5]:
data

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}

In [6]:
pd.DataFrame(data)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [7]:
import numpy as np

In [8]:
arr=np.array([[1,2,3],[5,4,3]])

In [9]:
arr

array([[1, 2, 3],
       [5, 4, 3]])

In [10]:
df=pd.DataFrame(arr,columns=["A","B","C"])

In [11]:
df

   A  B  C
0  1  2  3
1  5  4  3

In [12]:
df=pd.read_excel("data.xlsx")

In [13]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dell\anaconda3\envs\prithenv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\anaconda3\envs\prithenv\lib\site-packages (from openpyxl) (2.0.0)

In [14]:
df

  name  marks
0    a     12
1    s      3
2    d     45
3    f      6
4   hj     42

In [15]:
df=pd.read_csv("data.csv")

In [16]:
df

  name  marks
0    a     12
1    s      3
2    d     45
3    f      6
4   hj     42

In [19]:
df=pd.read_json("data.json")

In [20]:
df

             name  age
0        Prithesh   22
1  Pritheshshetty   29