In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [6]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [12]:
pd.merge(employees,departments,on="DeptID",how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
pd.merge(employees,departments,how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [14]:
pd.merge(employees,departments,how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [16]:
pd.concat([employees,departments])

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10          NaN
1    2.0      Bob      20          NaN
2    3.0  Charlie      30          NaN
0    NaN      NaN      10           HR
1    NaN      NaN      20  Engineering
2    NaN      NaN      40    Marketing

In [17]:
pd.concat([employees,departments],axis=1)

   EmpID     Name  DeptID  DeptID     DeptName
0      1    Alice      10      10           HR
1      2      Bob      20      20  Engineering
2      3  Charlie      30      40    Marketing