In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data2.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [5]:
df.sort_values(["Year","IMDb"])

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [6]:
df2=df.sort_values(["Year","IMDb"],ascending=False).copy()

In [7]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df2.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,7,Hrithik Roshan,War,2019,Action,475,6.5
6,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [9]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [10]:
df2.reset_index(drop=True)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [11]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [12]:
df2.reset_index(drop=True,inplace=True)

In [13]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [14]:
df2["Rank"]=df2["IMDb"].rank(method="dense",ascending=True).copy()

In [15]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,5.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0

In [16]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,5.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0

In [23]:
df2["Rank"]=df["IMDb"].rank(ascending=False,method="dense").copy()

In [24]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,9.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,11.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,2.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,4.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,7.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,10.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,8.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,3.0

In [26]:
df2.sort_values("Rank")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
5,Hrithik Roshan,War,2019,Action,475,6.5,2.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,3.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,4.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,7.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,8.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,9.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,10.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,11.0

In [27]:
df2.rename(columns={"Genre":"Type"},inplace=True)

In [28]:
df2

,Actor,Film,Year,Type,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,9.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,11.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,2.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,4.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,7.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,10.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,8.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,3.0

In [45]:
cols=["Type"]+[col for col in df2.columns if col!="Type"]

In [46]:
cols

['Type', 'Actor', 'Film', 'Year', 'BoxOffice(INR Crore)', 'IMDb', 'Rank']

In [47]:
df2.columns

Index(['Actor', 'Film', 'Year', 'Type', 'BoxOffice(INR Crore)', 'IMDb',
       'Rank'],
      dtype='str')

In [ ]:
df2.co